"""empty message

Revision ID: 15be3057ddc4
Revises: 16c6202c3d54
Create Date: 2020-10-31 19:23:36.868482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15be3057ddc4'
down_revision = '16c6202c3d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('date', sa.String(length=150), nullable=True))
    op.drop_column('information', 'month')
    op.drop_column('information', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('information', sa.Column('month', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('information', 'date')
    # ### end Alembic commands ###
