"""empty message

Revision ID: 16c6202c3d54
Revises: 6d4822e10168
Create Date: 2020-10-25 20:22:58.504462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16c6202c3d54'
down_revision = '6d4822e10168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'supplier_stock_per_product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('supplier_stock_per_product', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
