"""empty message

Revision ID: 64a7d1b9d332
Revises: ea8b0d7f25a6
Create Date: 2020-10-23 12:52:42.798135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a7d1b9d332'
down_revision = 'ea8b0d7f25a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sku_id', table_name='product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sku_id', 'product', ['sku_id'], unique=True)
    # ### end Alembic commands ###
