"""empty message

Revision ID: 6d4822e10168
Revises: 8a527b6ffb22
Create Date: 2020-10-24 21:46:27.081968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d4822e10168'
down_revision = '8a527b6ffb22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('img', sa.Column('data', sa.LargeBinary(), nullable=True))
    op.drop_column('img', 'mimetype')
    op.drop_column('img', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('img', sa.Column('img', mysql.TEXT(), nullable=True))
    op.add_column('img', sa.Column('mimetype', mysql.TEXT(), nullable=True))
    op.drop_column('img', 'data')
    # ### end Alembic commands ###
